apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
  namespace: {{ template "runhub.namespaceEnvReleaseChart" . }}
spec:
  params:
    - name: service
      type: string
    - name: subroute-tag
      type: string
    - name: image
      type: string
    - name: image-tag
      type: string
    - name: protocol
      type: string
    - name: domain
      type: string
    - name: initialScale
      type: string
    - name: minScale
      type: string
  workspaces:
    - name: prod-kubeconfig
      readOnly: true
      optional: true
  steps:
    - name: deploy
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:{{ template "runhub.dev.knImageTag" . }}
      script: |
        IMAGE='$(params.image):$(params.image-tag)'
        REVISION_NAME='$(params.service)-$(params.image-tag)-$(context.taskRun.uid)'

        if [ '$(params.protocol)' = 'http' ]; then
          DISABLE_AUTO_TLS='true'
        else
          DISABLE_AUTO_TLS='false'
        fi

        if [ -n '$(workspaces.prod-kubeconfig.path)' ]; then
          export KUBECONFIG=$(workspaces.prod-kubeconfig.path)/kubeconfig
        fi

        if [ -z '$(params.subroute-tag)' ]; then
          if ! kn service describe '$(params.service)'; then
            kn service create '$(params.service)' \
              --image "${IMAGE:?}" \
              --revision-name "${REVISION_NAME:?}" \
              --scale-init '$(params.initialScale)' \
              --scale-min '$(params.minScale)' \
              --annotation-service domain='$(params.domain)' \
              --annotation-service networking.knative.dev/disableAutoTLS="${DISABLE_AUTO_TLS:?}" \
              {{- range $serviceName, $service := .Values.services }}
              --env 'RUNHUB_SERVICE_{{ upper $serviceName }}_URL=$(params.protocol)://{{ $service.subdomain }}.$(params.domain)' \
              {{- end }}
              --pull-secret container-registry-dockerconfigjson
            kn service update '$(params.service)' \
              --traffic "${REVISION_NAME:?}=100"
          else
            kn service update '$(params.service)' \
              --image "${IMAGE:?}" \
              --revision-name "${REVISION_NAME:?}" \
              --scale-init '$(params.initialScale)' \
              --scale-min '$(params.minScale)' \
              --annotation-service domain='$(params.domain)' \
              --annotation-service networking.knative.dev/disableAutoTLS="${DISABLE_AUTO_TLS:?}" \
              {{- range $serviceName, $service := .Values.services }}
              --env 'RUNHUB_SERVICE_{{ upper $serviceName }}_URL=$(params.protocol)://{{ $service.subdomain }}.$(params.domain)' \
              {{- end }}
              --traffic "${REVISION_NAME:?}=100"
          fi
        else
          kn service update '$(params.service)' --untag '$(params.subroute-tag)' || true
          kn service update '$(params.service)' \
            --image "${IMAGE:?}" \
            --revision-name "${REVISION_NAME:?}" \
            --tag "${REVISION_NAME:?}"='$(params.subroute-tag)' \
            --scale-init '$(params.initialScale)' \
            --scale-min '$(params.minScale)' \
            --annotation-service domain='$(params.domain)' \
            --annotation-service networking.knative.dev/disableAutoTLS="${DISABLE_AUTO_TLS:?}" \
              {{- range $serviceName, $service := .Values.services }}
              --env 'RUNHUB_SERVICE_{{ upper $serviceName }}_URL=$(params.protocol)://$(params.subroute-tag)-{{ $service.subdomain }}.$(params.domain)'
              {{- end }}
        fi
