apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: undeploy
  namespace: {{ template "runhub.namespaceReleaseChart" . }}
spec:
  params:
    - name: service
      type: string
    - name: subroute-tag
      type: string
  steps:
    - name: undeploy
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:v0.20.0@sha256:688c8d46c77ca515fdc9f0fdf6abc28178929bd07ca98df9fea2f3f2d15150fc
      script: |
        kn service update '$(params.service)' --untag '$(params.subroute-tag)'
