apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: undeploy
  namespace: {{ template "runhub.namespaceReleaseChart" . }}
spec:
  params:
    - name: service
      type: string
    - name: subroute-tag
      type: string
  steps:
    - name: undeploy
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:{{ template "runhub.dev.knImageTag" . }}
      script: |
        kn service update '$(params.service)' --untag '$(params.subroute-tag)'
