apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy
  namespace: {{ template "runhub-app.namespaceEnvironmentReleaseChart" . }}
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - get
      - create
      - update
      - watch
  - apiGroups:
      - serving.knative.dev
    resources:
      - revisions
    verbs:
      - get
