apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: undeploy
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - get
      - update
      - watch
  - apiGroups:
      - serving.knative.dev
    resources:
      - revisions
    verbs:
      - get
