apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: tag
      type: string
    - name: cache-from-tag
      type: string
    - name: environment
      type: string
  workspaces:
  {{- range $serviceName, $service := .Values.services }}
    - name: src-{{ $serviceName }}
  {{- end }}
    - name: dockerfile
  {{- if .Values.release }}
    - name: prod-kubeconfig
  {{- end }}
  tasks:
  {{- range $serviceName, $service := .Values.services }}
    - name: build-{{ $serviceName }}
      taskRef:
        name: build
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: src-path
          value: {{ $service.srcPath }}
        - name: service
          value: {{ $serviceName }}
        - name: tag
          value: $(params.tag)
        - name: cache-from-tag
          value: $(params.cache-from-tag)
      workspaces:
        - name: dockerfile
          workspace: dockerfile
        - name: src
          workspace: src-{{ $serviceName }}
    - name: deploy-{{ $serviceName }}
      runAfter:
      {{- range $serviceName, $service := $.Values.services }}
        - build-{{ $serviceName }}
      {{- end }}
      taskRef:
        name: deploy
      params:
        - name: service
          value: {{ $service.subdomain }}
        - name: image
          value: {{ $serviceName }}
        - name: tag
          value: $(params.tag)
        - name: environment
          value: $(params.environment)
    {{- if $.Values.release }}
      workspaces:
        - name: prod-kubeconfig
          workspace: prod-kubeconfig
    {{- end }}
    - name: expose-{{ $serviceName }}
      runAfter:
      {{- range $serviceName, $service := $.Values.services }}
        - deploy-{{ $serviceName }}
      {{- end }}
      taskRef:
        name: expose
      params:
        - name: service
          value: {{ $service.subdomain }}
        - name: tag
          value: $(params.tag)
        - name: environment
          value: $(params.environment)
    {{- if $.Values.release }}
      workspaces:
        - name: prod-kubeconfig
          workspace: prod-kubeconfig
    {{- end }}
  {{- end }}
