apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: undeploy
spec:
  params:
    - name: tag
      type: string
  tasks:
    - name: convert-tag-to-subdomain
      taskRef:
        name: sanitize
      params:
        - name: input
          value: $(params.tag)
    {{- range $serviceName, $service := .Values.global.services }}
    - name: unexpose-{{ $serviceName }}
      runAfter:
        - convert-tag-to-subdomain
      taskRef:
        name: unexpose
      params:
        - name: service
          value: {{ $serviceName }}
        - name: tag
          value: $(tasks.convert-tag-to-subdomain.results.output)
    - name: undeploy-{{ $serviceName }}
      runAfter:
        - convert-tag-to-subdomain
      taskRef:
        name: undeploy
      params:
        - name: service
          value: {{ $serviceName }}
        - name: tag
          value: $(tasks.convert-tag-to-subdomain.results.output)
    {{- end }}
