apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: undeploy
spec:
  params:
    - name: service-tag
      type: string
  tasks:
    {{- range $serviceName, $service := .Values.services }}
    - name: undeploy-{{ $serviceName }}
      taskRef:
        name: undeploy
      params:
        - name: service
          value: {{ $service.subdomain }}
        - name: service-tag
          value: $(params.service-tag)
    {{- end }}
