apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: undeploy
spec:
  params:
    - name: tag
      type: string
  tasks:
    - name: sanitize-tag
      taskRef:
        name: sanitize
      params:
        - name: input
          value: $(params.tag)
    {{- range $serviceName, $service := .Values.global.services }}
    - name: unexpose-{{ $serviceName }}
      runAfter:
        - sanitize-tag
      taskRef:
        name: unexpose
      params:
        - name: service
          value: {{ $serviceName }}
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
    - name: undeploy-{{ $serviceName }}
      runAfter:
        - sanitize-tag
      taskRef:
        name: undeploy
      params:
        - name: service
          value: {{ $serviceName }}
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
    {{- end }}
