apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: service
      type: string
    - name: subroute-tag
      type: string
    - name: image
      type: string
    - name: image-tag
      type: string
    - name: main-route-tag
      type: string
    - name: main-route-image-tag
      type: string
  steps:
    - name: deploy
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:v0.19.1@sha256:d49c937341792a6144e61d251dc174688665c39c433dc0fcf468027ea4309ec6
      script: |
        kn service describe '$(params.service)' || \
          kn service create '$(params.service)' \
            --image '$(params.image):$(params.main-route-image-tag)' \
            --pull-secret container-registry-dockerconfigjson
        kn service update '$(params.service)' --untag '$(params.subroute-tag)' || true
        kn service update '$(params.service)' \
          --traffic '$(params.main-route-image-tag)=100' \
          --image '$(params.image):$(params.image-tag)' \
          {{- range $serviceName, $service := .Values.services }}
          --env 'RUNHUB_{{ upper $serviceName }}_URL=http://$(params.subroute-tag)-{{ $service.subdomain }}.{{ template "runhub.domainWithNamespace" $ }}' \
          {{- end }}
          --revision-name '$(params.service)-$(params.subroute-tag)-$(context.taskRun.uid)' \
          --tag '$(params.service)-$(params.subroute-tag)-$(context.taskRun.uid)=$(params.subroute-tag)'
