apiVersion: skaffold/v2beta13
kind: Config
deploy:
  helm:
    releases:
      - name: '{{.APP}}'
        chartPath: helm-charts/runhub-app
        namespace: dev-{{.APP}}
        createNamespace: true
        setValues:
          global.env.dev: true
        valuesFiles:
          - values-shared.yaml
          - values-dev.yaml
          - values-dev-infra.yaml
        skipBuildDependencies: true
      - name: '{{.APP}}'
        chartPath: helm-charts/runhub-app
        namespace: prod-{{.APP}}
        createNamespace: true
        setValues:
          global.env.prod: true
        valuesFiles:
          - values-shared.yaml
          - values-prod.yaml
          - values-prod-infra.yaml
        skipBuildDependencies: true
