apiVersion: skaffold/v2beta10
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: dev-runhub
        setValues:
          environment.development: true
        createNamespace: true
        skipBuildDependencies: true
      - name: app
        chartPath: charts/runhub
        namespace: dev-runhub
        valuesFiles:
          - values.yaml
        setValues:
          environment.development: true
          development.domain: dev.127.0.0.1.xip.io
        skipBuildDependencies: true
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: prod-runhub
        setValues:
          environment.production: true
          knative-crds.enabled: false
        createNamespace: true
        skipBuildDependencies: true
      - name: app
        chartPath: charts/runhub
        namespace: prod-runhub
        setValues:
          environment.production: true
          knative.enabled: false
        skipBuildDependencies: true
    flags:
      install:
        - --atomic
      upgrade:
        - --atomic
