apiVersion: skaffold/v2beta12
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-deps-crds
        chartPath: charts/runhub-deps-crds
        namespace: runhub-deps
        createNamespace: true
        setValues:
          global.environment.dev: true
        skipBuildDependencies: true
      - name: runhub-deps-operators
        chartPath: charts/runhub-deps-operators
        namespace: runhub-deps
        setValues:
          global.environment.dev: true
        skipBuildDependencies: true
      - name: runhub-deps
        chartPath: charts/runhub-deps
        namespace: runhub-deps
        setValues:
          global.environment.dev: true
        valuesFiles:
          - values-deps.yaml
        skipBuildDependencies: true
      - name: '{{.RUNHUB_APP}}'
        chartPath: charts/runhub-app
        namespace: dev-{{.RUNHUB_APP}}
        createNamespace: true
        setValues:
          global.environment.dev: true
        valuesFiles:
          - values-dev-and-prod.yaml
          - values-dev.yaml
        skipBuildDependencies: true
      - name: '{{.RUNHUB_APP}}'
        chartPath: charts/runhub-app
        namespace: prod-{{.RUNHUB_APP}}
        createNamespace: true
        setValues:
          global.environment.prod: true
        valuesFiles:
          - values-dev-and-prod.yaml
        skipBuildDependencies: true
profiles:
  - name: install-istio
    deploy:
      helm:
        releases:
          - name: runhub-deps-crds
            chartPath: charts/runhub-deps-crds
            namespace: runhub-deps
            createNamespace: true
            setValues:
              global.environment.dev: true
              cert-manager-crds.enabled: false
              knative-operator-crds.enabled: false
              tekton-crds.enabled: false
            skipBuildDependencies: true
          - name: runhub-deps-operators
            chartPath: charts/runhub-deps-operators
            namespace: runhub-deps
            setValues:
              global.environment.dev: true
              knative-operator.enabled: false
            skipBuildDependencies: true
          - name: runhub-deps
            chartPath: charts/runhub-deps
            namespace: runhub-deps
            setValues:
              global.environment.dev: true
              cert-manager.enabled: false
              knative.enabled: false
              tekton.enabled: false
            valuesFiles:
              - values-deps.yaml
            skipBuildDependencies: true
