apiVersion: skaffold/v2beta10
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: dev-runhub
        setValues:
          global.environment.dev: true
        createNamespace: true
        skipBuildDependencies: true
      - name: app
        chartPath: charts/runhub
        namespace: dev-runhub
        valuesFiles:
          - values-development.yaml
          - values-global.yaml
        setFiles:
          dev.gitCredentials.password: password-git.txt
          global.containerRegistryCredentials.password: password-containerRegistry.txt
        setValues:
          global.environment.dev: true
          dev.domain: dev.127.0.0.1.xip.io
          dev.release.prod-domain: 127.0.0.1.xip.io
        skipBuildDependencies: true
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: prod-runhub
        setValues:
          global.environment.prod: true
          knative-crds.enabled: false
        createNamespace: true
        skipBuildDependencies: true
      - name: app
        chartPath: charts/runhub
        namespace: prod-runhub
        valuesFiles:
          - values-global.yaml
        setFiles:
          global.containerRegistryCredentials.password: password-containerRegistry.txt
        setValues:
          global.environment.prod: true
          knative.enabled: false
        skipBuildDependencies: true
    flags:
      install:
        - --atomic
      upgrade:
        - --atomic
