apiVersion: skaffold/v2beta11
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-deps-crds
        chartPath: charts/runhub-deps-crds
        namespace: dev-runhub
        createNamespace: true
        setValues:
          global.environment.dev: true
        skipBuildDependencies: true
      - name: runhub-deps-operators
        chartPath: charts/runhub-deps-operators
        namespace: dev-runhub
        setValues:
          global.environment.dev: true
        skipBuildDependencies: true
      - name: runhub-deps
        chartPath: charts/runhub-deps
        namespace: dev-runhub
        setValues:
          global.environment.dev: true
        valuesFiles:
          - values-deps.yaml
        skipBuildDependencies: true
      - name: '{{.RUNHUB_APP}}'
        chartPath: charts/runhub-app
        namespace: dev-runhub
        setValues:
          global.environment.dev: true
        valuesFiles:
          - values-dev-and-prod.yaml
          - values-dev.yaml
        skipBuildDependencies: true
      - name: '{{.RUNHUB_APP}}'
        chartPath: charts/runhub-app
        namespace: prod-runhub
        createNamespace: true
        setValues:
          global.environment.prod: true
        valuesFiles:
          - values-dev-and-prod.yaml
        skipBuildDependencies: true
