apiVersion: skaffold/v2beta12
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-deps-crds
        chartPath: charts/runhub-deps-crds
        namespace: runhub-deps
        createNamespace: true
        setValues:
          global.environment.dev: true
        skipBuildDependencies: true
      - name: runhub-deps
        chartPath: charts/runhub-deps
        namespace: runhub-deps
        setValues:
          global.environment.dev: true
        skipBuildDependencies: true
      - name: '{{.RUNHUB_APP}}'
        chartPath: charts/runhub-app
        namespace: dev-{{.RUNHUB_APP}}
        createNamespace: true
        setValues:
          global.environment.dev: true
        valuesFiles:
          - values.yaml
        skipBuildDependencies: true
      - name: '{{.RUNHUB_APP}}'
        chartPath: charts/runhub-app
        namespace: prod-{{.RUNHUB_APP}}
        createNamespace: true
        setValues:
          global.environment.prod: true
        valuesFiles:
          - values.yaml
        skipBuildDependencies: true
