apiVersion: skaffold/v2beta10
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: runhub
        createNamespace: true
        skipBuildDependencies: true
      - name: dev-app
        chartPath: charts/runhub
        namespace: runhub
        valuesFiles:
          - values.yaml
        setValues:
          domain: dev.127.0.0.1.xip.io
        skipBuildDependencies: true
    flags:
      install:
        - --atomic
      upgrade:
        - --atomic
