apiVersion: skaffold/v2beta10
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: runhub
        createNamespace: true
      - name: runhub
        chartPath: charts/runhub
        namespace: runhub
        valuesFiles:
          - values.yaml
    flags:
      install:
        - --atomic
      upgrade:
        - --atomic
