apiVersion: skaffold/v2beta10
kind: Config
deploy:
  helm:
    releases:
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: dev-runhub
        createNamespace: true
        setValues:
          global.environment.dev: true
        skipBuildDependencies: true
      - name: app
        chartPath: charts/runhub
        namespace: dev-runhub
        setValues:
          global.environment.dev: true
        valuesFiles:
          - values-development.yaml
          - values-shared.yaml
        skipBuildDependencies: true
      - name: runhub-crds
        chartPath: charts/runhub-crds
        namespace: prod-runhub
        createNamespace: true
        setValues:
          global.environment.prod: true
          knative-crds.enabled: false
        skipBuildDependencies: true
      - name: app
        chartPath: charts/runhub
        namespace: prod-runhub
        setValues:
          global.environment.prod: true
          knative.enabled: false
        valuesFiles:
          - values-shared.yaml
        skipBuildDependencies: true
    flags:
      install:
        - --atomic
      upgrade:
        - --atomic
