apiVersion: skaffold/v2beta14
kind: Config
deploy:
  helm:
    releases:
      - name: '{{.APP}}'
        chartPath: helm-charts/runhub-app
        namespace: dev-{{.APP}}
        createNamespace: true
        setValues:
          global.env.dev: true
        valuesFiles:
          - config/values-shared.yaml
          - config/values-dev.yaml
          - config/generated/values-dev-from-dev.yaml
          - config/generated/values-dev-from-prod.yaml
        skipBuildDependencies: true
      - name: '{{.APP}}'
        chartPath: helm-charts/runhub-app
        namespace: prod-{{.APP}}
        createNamespace: true
        setValues:
          global.env.prod: true
        valuesFiles:
          - config/values-shared.yaml
          - config/values-prod.yaml
          - config/generated/values-prod-from-prod.yaml
          - config/generated/values-prod-from-dev.yaml
        skipBuildDependencies: true
