apiVersion: skaffold/v2beta12
kind: Config
deploy:
  helm:
    releases:
      - name: '{{.APP}}'
        chartPath: charts/runhub-app
        namespace: dev-{{.APP}}
        createNamespace: true
        setValues:
          global.env.dev: true
        valuesFiles:
          - values.yaml
        skipBuildDependencies: true
      - name: '{{.APP}}'
        chartPath: charts/runhub-app
        namespace: prod-{{.APP}}
        createNamespace: true
        setValues:
          global.env.prod: true
        valuesFiles:
          - values.yaml
        skipBuildDependencies: true
