apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "runhub.namespaceEnvReleaseChart" . }}-git-webhook
rules:
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - clustertriggerbindings
    verbs:
      - list
      - get
      - watch
