apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
  namespace: {{ template "runhub.development.namespaceReleaseChart" . }}
spec:
  params:
    - name: src-path
      type: string
    - name: image-path-with-hostname
      type: string
    - name: image-name
      type: string
    - name: image-tag
      type: string
    - name: cache-from-image-tag
      type: string
  workspaces:
    - name: dockerfile
    - name: src
  steps:
    - name: build
      image: moby/buildkit:v0.8.1@sha256:ecd5ad4910c322cad6995f8a1a0805d9da4b09ed4aaef40627f5bcb8ebf74068
      securityContext:
        privileged: true
      script: |
        IMAGE='$(params.image-path-with-hostname)/$(params.image-name)'
        CACHE_IMAGE='$(params.image-path-with-hostname)/cache/$(params.image-name)'

        buildctl-daemonless.sh \
          build \
            --frontend dockerfile.v0 \
            --local dockerfile='$(workspaces.dockerfile.path)' \
            --local context='$(workspaces.src.path)' \
            --opt build-arg:SRC_PATH='$(params.src-path)' \
            --output type=image,name="${IMAGE:?}":'$(params.image-tag)',push=true \
            --export-cache type=registry,mode=max,ref="${CACHE_IMAGE:?}":'$(params.image-tag)' \
            --import-cache type=registry,\"ref="${CACHE_IMAGE:?}":'$(params.image-tag)',"${CACHE_IMAGE:?}":'$(params.cache-from-image-tag)'\"
