apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
  namespace: {{ template "runhub.development.namespaceReleaseChart" . }}
spec:
  params:
    - name: service
      type: string
    - name: subroute-tag
      type: string
    - name: image
      type: string
    - name: image-tag
      type: string
  steps:
    - name: deploy
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:v0.19.1@sha256:d49c937341792a6144e61d251dc174688665c39c433dc0fcf468027ea4309ec6
      script: |
        IMAGE='$(params.image):$(params.image-tag)'
        REVISION_NAME='$(params.service)-$(params.image-tag)-$(context.taskRun.uid)'

        if [ -z '$(params.subroute-tag)' ]; then
          if ! kn service describe '$(params.service)'; then
            kn service create '$(params.service)' \
              --annotation-service domain='{{ .Values.domain }}' \
              --scale-init 0 \
              --pull-secret container-registry-dockerconfigjson \
              --image "${IMAGE:?}" \
              {{- range $serviceName, $service := .Values.services }}
              --env 'RUNHUB_SERVICE_{{ upper $serviceName }}_URL=http://{{ $service.subdomain }}.{{ $.Values.domain }}' \
              {{- end }}
              --revision-name "${REVISION_NAME:?}"
            kn service update '$(params.service)' \
              --traffic "${REVISION_NAME:?}=100"
          else
            kn service update '$(params.service)' \
              --image "${IMAGE:?}" \
              {{- range $serviceName, $service := .Values.services }}
              --env 'RUNHUB_SERVICE_{{ upper $serviceName }}_URL=http://{{ $service.subdomain }}.{{ $.Values.domain }}' \
              {{- end }}
              --revision-name "${REVISION_NAME:?}" \
              --traffic "${REVISION_NAME:?}=100"
          fi
        else
          kn service update '$(params.service)' --untag '$(params.subroute-tag)' || true
          kn service update '$(params.service)' \
            --image "${IMAGE:?}" \
              {{- range $serviceName, $service := .Values.services }}
              --env 'RUNHUB_SERVICE_{{ upper $serviceName }}_URL=http://$(params.subroute-tag)-{{ $service.subdomain }}.{{ $.Values.domain }}' \
              {{- end }}
            --revision-name "${REVISION_NAME:?}" \
            --tag "${REVISION_NAME:?}"='$(params.subroute-tag)'
        fi
