apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: tag
    - name: cache-from-tag
    - name: env
    - name: git-default-branch
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-
      spec:
        serviceAccountName: build-deploy
        pipelineRef:
          name: build-deploy
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: tag
            value: $(tt.params.tag)
          - name: cache-from-tag
            value: $(tt.params.cache-from-tag)
          - name: env
            value: $(tt.params.env)
          - name: git-default-branch
            value: $(tt.params.git-default-branch)
        workspaces:
          - name: app-chart
            configMap:
              name: app-chart
          - name: app-chart-templates
            configMap:
              name: app-chart-templates
