apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: tag
    - name: cache-from-tag
    - name: env
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-
      spec:
        serviceAccountName: build-deploy
        pipelineRef:
          name: build-deploy
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: tag
            value: $(tt.params.tag)
          - name: cache-from-tag
            value: $(tt.params.cache-from-tag)
          - name: env
            value: $(tt.params.env)
        workspaces:
        {{- range $serviceName, $service := .Values.global.services }}
          - name: build-context-{{ $serviceName }}
            emptyDir: {}
        {{- end }}
          - name: dockerfile
            configMap:
              name: dockerfile
        {{- if (and .Values.release .Values.release.prodKubernetesCredentials) }}
          - name: prod-kubeconfig
            secret:
              secretName: prod-kubeconfig-opaque
        {{- end }}
