apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: expose
spec:
  params:
    - name: service
      type: string
    - name: subdomain
      type: string
    - name: tag
      type: string
    - name: environment
      type: string
{{- if .Values.release }}
  workspaces:
    - name: prod-kubeconfig
      readOnly: true
{{- end }}
  steps:
    - name: expose
      image: gcr.io/bitnami-containers/kubectl:{{ template "runhub-app.dev.kubectlImageTag" . }}
      script: |
        {{ include "runhub-app.dev.convertToDNSLabelShellFunction" . | nindent 8 }}

        TAG_DNS_LABEL="$(convert_to_dns_label '$(params.tag)')"

        if [ '$(params.environment)' = 'dev' ]; then
          DOMAIN='{{ $.Values.domain }}'
          SUBDOMAIN="${TAG_DNS_LABEL:?}"'.$(params.subdomain)'
        elif [ '$(params.environment)' = 'prod' ]; then
          export KUBECONFIG='$(workspaces.prod-kubeconfig.path)/kubeconfig'
          DOMAIN='{{ $.Values.global.prodDomain }}'
          SUBDOMAIN='$(params.subdomain)'
        fi

        kubectl apply --filename - <<EOF
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        metadata:
          name: ${TAG_DNS_LABEL:?}
          namespace: $(params.environment)-{{ .Release.Name }}-$(params.service)
        spec:
          gateways:
            - $(params.environment)-{{ .Release.Name }}/gateway
          hosts:
            - ${SUBDOMAIN:?}.${DOMAIN:?}
          http:
            - rewrite:
                authority: ${TAG_DNS_LABEL:?}.$(params.environment)-{{ .Release.Name }}-$(params.service).svc.cluster.local
              route:
                - destination:
                    host: ${TAG_DNS_LABEL:?}.$(params.environment)-{{ .Release.Name }}-$(params.service).svc.cluster.local
        EOF
    - name: migrate-traffic
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:{{ template "runhub-app.dev.knImageTag" . }}
      script: |
        {{ include "runhub-app.dev.convertToDNSLabelShellFunction" . | nindent 8 }}

        TAG_DNS_LABEL="$(convert_to_dns_label '$(params.tag)')"

        if [ '$(params.environment)' = 'prod' ]; then
          export KUBECONFIG='$(workspaces.prod-kubeconfig.path)/kubeconfig'
        fi

        REVISION=$(kn service describe "${TAG_DNS_LABEL:?}" \
          --namespace '$(params.environment)-{{ .Release.Name }}-$(params.service)' \
          --output go-template --template '{{"{{"}} .status.latestReadyRevisionName }}')

        kn service update "${TAG_DNS_LABEL:?}" \
          --namespace '$(params.environment)-{{ .Release.Name }}-$(params.service)' \
          --traffic "${REVISION:?}=100"
