apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-sha
spec:
  params:
    - name: service
      type: string
    - name: tag
      type: string
  results:
    - name: sha
  steps:
    - name: get-sha
      image: quay.io/skopeo/stable:master
      script: |
        IMAGE='{{ template "runhub-app.dev.imagePathWithRegistry" . }}/$(params.service)'

        skopeo inspect "docker://${IMAGE:?}"':$(params.tag)' --format '{{"{{"}} .Digest }}' \
          | tr -d '\n' > '$(results.sha.path)'
