apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: migrate-traffic
spec:
  params:
    - name: service
      type: string
    - name: service-tag
      type: string
    - name: service-revision
      type: string
  workspaces:
    - name: prod-kubeconfig
      readOnly: true
      optional: true
  steps:
    - name: migrate-traffic
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:{{ template "runhub-app.dev.knImageTag" . }}
      script: |
        if [ '$(workspaces.prod-kubeconfig.path)' ]; then
          export KUBECONFIG=$(workspaces.prod-kubeconfig.path)/kubeconfig
        fi

        if [ '$(params.service-tag)' ]; then
          set -- --tag '$(params.service-revision)=$(params.service-tag)'

          if ! kn service update '$(params.service)' --untag '$(params.service-tag)' "$@"; then
            kn service update '$(params.service)' "$@"
          fi
        else
          kn service update '$(params.service)' \
            --traffic '$(params.service-revision)'=100
        fi
