apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sanitize
spec:
  params:
    - name: input
      type: string
  results:
    - name: output
  steps:
    - name: sanitize
      image: alpine:3.13.2@sha256:a75afd8b57e7f34e4dad8d65e2c7ba2e1975c795ce1ee22fa34f8cf46f96a3be
      script: |
        printf '%s' '$(params.input)' \
          | printf '%s' "$(cut -c 1-63)" \
          | tr '[:upper:]' '[:lower:]' \
          | tr -c '[:alnum:]' '-' \
          | sed 's/^-*//' \
          | sed 's/-*$//' \
          > '$(results.output.path)'
