apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: undeploy
spec:
  params:
    - name: service
      type: string
    - name: service-tag
      type: string
  steps:
    - name: undeploy
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:{{ template "runhub-app.dev.knImageTag" . }}
      script: |
        if [ '$(params.service-tag)' ]; then
          SERVICE='$(params.service)-$(params.service-tag)'
        else
          SERVICE='$(params.service)'
        fi

        kn service delete "${SERVICE:?}"
