apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unexpose
spec:
  params:
    - name: service
      type: string
    - name: tag
      type: string
  steps:
    - name: unexpose
      image: gcr.io/bitnami-containers/kubectl:{{ template "runhub-app.dev.kubectlImageTag" . }}
      script: |
        {{ include "runhub-app.dev.convertToDNSLabelShellFunction" . | nindent 8 }}

        TAG_DNS_LABEL="$(convert_to_dns_label '$(params.tag)')"

        kubectl delete virtualservice "${TAG_DNS_LABEL:?}" \
          --namespace '{{ .Release.Namespace }}-$(params.service)'
