apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: unexpose
spec:
  params:
    - name: service
      type: string
    - name: image-tag
      type: string
  steps:
    - name: unexpose
      image: gcr.io/bitnami-containers/kubectl:{{ template "runhub-app.dev.kubectlImageTag" . }}
      script: |
        if [ '$(params.image-tag)' ]; then
          SERVICE='$(params.service)-$(params.image-tag)'
        else
          SERVICE='$(params.service)'
        fi

        kubectl delete virtualservice ${SERVICE:?}
