apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: expose
spec:
  params:
    - name: service
      type: string
    - name: subdomain
      type: string
    - name: tag
      type: string
    - name: env
      type: string
{{- if (and .Values.release .Values.release.prodKubernetesCredentials) }}
  workspaces:
    - name: prod-kubeconfig
      readOnly: true
{{- end }}
  steps:
    - name: expose
      image: gcr.io/bitnami-containers/kubectl:{{ template "runhub.dev.kubectlImageTag" . }}
      script: |
        if [ '$(params.env)' = 'dev' ]; then
          DOMAIN='{{ $.Values.domain }}'
          SUBDOMAIN='$(params.tag).$(params.subdomain)'
          SERVICE_NAME='$(params.tag)-$(params.service)'
        elif [ '$(params.env)' = 'prod' ]; then
          export KUBECONFIG='$(workspaces.prod-kubeconfig.path)/kubeconfig'
          DOMAIN='{{ $.Values.global.prodDomain }}'
          SUBDOMAIN='$(params.subdomain)'
          SERVICE_NAME='$(params.env)-$(params.service)'
        fi

        kubectl apply --filename - <<EOF
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        metadata:
          name: ${SERVICE_NAME:?}
          namespace: $(params.env)-{{ .Release.Name }}-app
        spec:
          gateways:
            - $(params.env)-{{ .Release.Name }}/gateway
          hosts:
            - ${SUBDOMAIN:?}.${DOMAIN:?}
          http:
            - rewrite:
                authority: ${SERVICE_NAME:?}.$(params.env)-{{ .Release.Name }}-app.svc.cluster.local
              route:
                - destination:
                    host: ${SERVICE_NAME:?}.$(params.env)-{{ .Release.Name }}-app.svc.cluster.local
        EOF
    - name: migrate-traffic
      image: gcr.io/knative-releases/knative.dev/client/cmd/kn:{{ template "runhub.dev.knImageTag" . }}
      script: |
        if [ '$(params.env)' = 'dev' ]; then
          SERVICE_NAME='$(params.tag)-$(params.service)'
        elif [ '$(params.env)' = 'prod' ]; then
          export KUBECONFIG='$(workspaces.prod-kubeconfig.path)/kubeconfig'
          SERVICE_NAME='$(params.env)-$(params.service)'
        fi

        REVISION="$(kn service describe "${SERVICE_NAME:?}" \
          --namespace '$(params.env)-{{ .Release.Name }}-app' \
          --output jsonpath='{ .status.latestReadyRevisionName }')"

        kn service update "${SERVICE_NAME:?}" \
          --namespace '$(params.env)-{{ .Release.Name }}-app' \
          --traffic "${REVISION:?}=100"
