apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sanitize
spec:
  params:
    - name: input
      type: string
  results:
    - name: output
  steps:
    - name: sanitize
      image: alpine:{{ template "runhub.dev.alpineImageTag" . }}
      script: |
        printf '%s' '$(params.input)' \
          | printf '%s' "$(cut -c 1-63)" \
          | tr '[:upper:]' '[:lower:]' \
          | tr -c '[:alnum:]' '-' \
          | sed 's/^-*//' \
          | sed 's/-*$//' \
          > '$(results.output.path)'
