apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: git-webhook
  namespace: {{ template "runhub-app.namespaceEnvironmentReleaseChart" . }}
  annotations:
    domain: {{ .Values.domain }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/initialScale: '1'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - args:
            - --el-name=git-webhook
            - --el-namespace=dev-app-runhub
            - --port=8000
            - --readtimeout=5
            - --writetimeout=40
            - --idletimeout=120
            - --timeouthandler=30
            - --is-multi-ns=false
            - --tls-cert=
            - --tls-key=
          env:
            - name: SYSTEM_NAMESPACE
              value: {{ template "runhub-app.namespaceEnvironmentReleaseChart" . }}
            - name: TEKTON_INSTALL_NAMESPACE
              value: tekton-pipelines
          image: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.11.2@sha256:ad7e626c0928fb762cb9880a29c18b15a30d44af405b7f102e8a18f21b640b2c
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /live
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: event-listener
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /live
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
          securityContext:
            runAsUser: 65532
      serviceAccountName: git-webhook
      volumes:
        - configMap:
            defaultMode: 420
            name: config-logging-triggers
          name: config-logging
