apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: undeploy-on-git-push-delete-branch
spec:
  interceptors:
    - github:
        secretRef:
          secretName: git-webhook-opaque
          secretKey: secret
        eventTypes:
          - push
    - cel:
        overlays:
          - key: ref_type
            expression: body.ref.split('/', 3)[1]
          - key: branch
            expression: body.ref.split('/', 3)[2]
    - cel:
        filter: extensions.ref_type == 'heads' && body.deleted
  {{- with .Values.release }}
  {{- if (and .prodKubernetesCredentials $.Values.global.prodDomain) }}
    - cel:
        filter: extensions.branch != '{{ .prodBranch }}'
  {{- end }}
  {{- end }}
  bindings:
    - ref: undeploy-on-git-push-delete-branch
  template:
    ref: undeploy
