{{- range $serviceName, $service := .Values.global.services }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy
  namespace: {{ template "runhub-app.environment" $ }}-{{ $.Release.Name }}-{{ $serviceName }}
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - get
      - create
      - update
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - get
      - create
      - patch
---
{{- end }}
