apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
spec:
  servers:
    - hosts: {{ include "runhub-app.hosts" . | nindent 8 }}
      port:
        name: http
        protocol: HTTP
        number: 80
{{- with .Values.global }}
  {{- if and .tls (or .environment.dev (and .environment.prod .prodDomain)) }}
      tls:
        httpsRedirect: true
    - hosts: {{ include "runhub-app.hosts" $ | nindent 8 }}
      port:
        name: https
        protocol: HTTPS
        number: 443
      tls:
        mode: SIMPLE
        credentialName: {{ $.Release.Namespace }}--certificate-tls
  {{- end }}
{{- end }}
