apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
spec:
  servers:
{{- with .Values.global }}
    - hosts:
    {{- if .environment.dev }}
      {{- range $serviceName, $service := .services }}
        - '*.{{ $service.subdomain }}.{{ template "runhub-app.environmentDomain" $ }}'
      {{- end }}
    {{- else if .environment.prod }}
        - '*.{{ template "runhub-app.environmentDomain" $ }}'
    {{- end }}
        - '*.runhub.{{ template "runhub-app.environmentDomain" $ }}'
      port:
        name: http
        protocol: HTTP
        number: 80
  {{- if and .tls (or .environment.dev (and .environment.prod .prodDomain)) }}
      tls:
        httpsRedirect: true
    - hosts:
    {{- if .environment.dev }}
      {{- range $serviceName, $service := .services }}
        - '*.{{ $service.subdomain }}.{{ template "runhub-app.environmentDomain" $ }}'
      {{- end }}
    {{- else if .environment.prod }}
        - '*.{{ template "runhub-app.environmentDomain" $ }}'
    {{- end }}
        - '*.runhub.{{ template "runhub-app.environmentDomain" $ }}'
      port:
        name: https
        protocol: HTTPS
        number: 443
      tls:
        mode: SIMPLE
        credentialName: {{ $.Release.Namespace }}--certificate-tls
  {{- end }}
{{- end }}
