{{- with .Values.global }}
{{- if or .environment.dev (and .environment.prod .prodDomain) }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: runhub
  namespace: {{ template "runhub-app.namespaceEnvironmentReleaseChart" $ }}
spec:
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - '*.runhub.{{ template "runhub-app.environmentDomain" $ }}'
{{- end }}
{{- end }}
