{{- with .Values.global }}
{{- if and .tls (or .environment.dev (and .environment.prod .prodDomain)) }}
apiVersion: networking.internal.knative.dev/v1alpha1
kind: Certificate
metadata:
  name: app
  namespace: {{ template "runhub.namespaceEnvironmentReleaseChart" $ }}
  annotations:
    networking.knative.dev/certificate.class: cert-manager.certificate.networking.knative.dev
  labels:
    networking.knative.dev/wildcardDomain: example.com
spec:
  dnsNames:
    {{- if .environment.dev }}
    - '*.{{ $.Values.dev.domain }}'
    {{- else if .environment.prod }}
    - '*.{{ .prodDomain }}'
    {{- end }}
  secretName: app-certificate-tls
{{- end }}
{{- end }}
