{{- with .Values.global }}
{{- if and .tls (or .environment.dev (and .environment.prod .prodDomain)) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Namespace }}
  namespace: istio-system
spec:
  dnsNames:
    - '*.runhub.{{ template "runhub-app.environmentDomain" $ }}'
  secretName: {{ $.Release.Namespace }}--certificate-tls
  issuerRef:
    name: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
