{{- with .Values.global }}
{{- if and .tls (or .environment.dev (and .environment.prod .prodDomain)) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Namespace }}
  namespace: istio-system
spec:
  dnsNames:
{{- if .environment.dev }}
  {{- range $serviceName, $service := .services }}
    - '*.{{ $service.subdomain }}.{{ template "runhub-app.environmentDomain" $ }}'
  {{- end }}
{{- else if .environment.prod }}
    - '*.{{ template "runhub-app.environmentDomain" $ }}'
{{- end }}
    - '*.runhub.{{ template "runhub-app.environmentDomain" $ }}'
  secretName: {{ $.Release.Namespace }}--certificate-tls
  issuerRef:
    name: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
