apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.7.6@sha256:3556894d90108857075033ecbce23b9fe24de4a2075da640cee2050ac74cf74d
          args:
            - --source=istio-gateway
            - --annotation-filter=external-dns-namespace={{ .Release.Namespace }}
            - --provider=cloudflare
            - --domain-filter={{ template "runhub-app.envDomain" . }}
            - --txt-owner-id={{ .Release.Namespace }}
          env:
            - name: CF_API_EMAIL
              value: {{ .Values.global.dns.cloudflareCredentials.email }}
            - name: CF_API_TOKEN
              value: {{ .Values.global.dns.cloudflareCredentials.apiToken }}
