apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-app
  namespace: {{ $.Release.Namespace }}-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-app
subjects:
  - kind: ServiceAccount
    name: build-deploy
    namespace: {{ $.Release.Namespace }}
