apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: undeploy-app
  namespace: {{ $.Release.Namespace }}-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: undeploy-app
subjects:
  - kind: ServiceAccount
    name: undeploy
    namespace: {{ $.Release.Namespace }}
