apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $.Release.Namespace }}
  namespace: istio-system
spec:
  acme:
    email: {{ .Values.global.tls.letsEncrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Namespace }}--lets-encrypt-private-key-opaque
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.global.tls.cloudflareCredentials.email }}
            apiTokenSecretRef:
              name: {{ .Release.Namespace }}--cloudflare-api-token-opaque
              key: api-token
