{{- with .Values.release }}
{{- with .prodKubernetesCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: prod-kubeconfig-opaque
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: prod
        cluster:
          server: {{ .clusterServer }}
          certificate-authority-data: {{ .clusterCertificateAuthorityData  }}
    users:
      - name: deploy
        user:
          token: {{ .serviceAccountToken }}
    contexts:
      - name: prod-deploy
        context:
          cluster: prod
          namespace: prod-{{ $.Release.Name }}
          user: deploy
    current-context: prod-deploy
{{- end }}
{{- end }}
