apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy
  namespace: {{ template "runhub.env" $ }}-{{ $.Release.Name }}-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy
subjects:
  - kind: ServiceAccount
    name: {{ if $.Values.global.env.dev }}build-{{ end }}deploy
    namespace: {{ $.Release.Namespace }}
