{{- range $serviceName, $service := .Values.global.services }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy
  namespace: {{ template "runhub.env" $ }}-{{ $.Release.Name }}-{{ $serviceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy
subjects:
  - kind: ServiceAccount
    name: {{ if $.Values.global.env.dev }}build-{{ end }}deploy
    namespace: {{ $.Release.Namespace }}
---
{{- end }}
