apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: tag
    - name: cache-from-tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-$(tt.params.tag)-
      spec:
        serviceAccountName: build-deploy
        pipelineRef:
          name: build-deploy
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: tag
            value: $(tt.params.tag)
          - name: cache-from-tag
            value: $(tt.params.cache-from-tag)
        workspaces:
        {{- range $serviceName, $service := .Values.services }}
          - name: src-{{ $serviceName }}
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        {{- end}}
          - name: dockerfile
            configMap:
              name: dockerfile
        {{- if .Values.release }}
          - name: prod-kubeconfig
            secret:
              secretName: prod-kubeconfig-opaque
        {{- end}}
