apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: undeploy
spec:
  params:
    - name: image-tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: undeploy-$(tt.params.image-tag)-
      spec:
        serviceAccountName: undeploy
        pipelineRef:
          name: undeploy
        params:
          - name: image-tag
            value: $(tt.params.image-tag)
