apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: undeploy
spec:
  params:
    - name: tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: undeploy-
      spec:
        serviceAccountName: undeploy
        pipelineRef:
          name: undeploy
        params:
          - name: tag
            value: $(tt.params.tag)
