apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger
  namespace: {{ template "runhub.dev.namespaceReleaseChart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trigger
subjects:
  - kind: ServiceAccount
    name: git-webhook
