apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy
  namespace: {{ template "runhub.namespaceEnvReleaseChart" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy
subjects:
  - kind: ServiceAccount
    name: build-deploy
