apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy
  namespace: {{ template "runhub.env" $ }}-{{ $.Release.Name }}-app
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - get
      - create
      - update
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
      - patch
