{{- with .Values.gitCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: git-basic-auth
  namespace: {{ template "runhub.namespaceEnvironmentReleaseChart" $ }}
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: {{ .username }}
  password: {{ .password }}
{{- end }}
