{{- with .Values.release }}
apiVersion: v1
kind: Secret
metadata:
  name: prod-kubeconfig-opaque
  namespace: {{ template "runhub.namespaceEnvironmentReleaseChart" $ }}
type: Opaque
stringData:
  kubeconfig: |
  {{- with .prodKubernetesCredentials }}
    apiVersion: v1
    kind: Config
    clusters:
      - name: production
        cluster:
          server: {{ .server }}
          certificate-authority-data: {{ .certificateAuthority | b64enc }}
    users:
      - name: production
        user:
          client-certificate-data: {{ .clientCertificate | b64enc }}
          client-key-data: {{ .clientKey | b64enc }}
    contexts:
      - name: production
        context:
          cluster: production
          user: production
          namespace: {{ template "runhub.dev.namespaceProdReleaseChart" $ }}
    current-context: production
  {{- end }}
{{- end }}
