apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-webhook
spec:
  triggers:
    - triggerRef: build-deploy-on-git-ping
    - triggerRef: build-deploy-on-git-push-branch
    - triggerRef: undeploy-on-git-push-delete-branch
  resources:
    customResource:
      apiVersion: serving.knative.dev/v1
      kind: Service
      metadata:
        labels:
          networking.knative.dev/visibility: cluster-local
      spec:
        template:
          metadata:
            annotations:
              autoscaling.knative.dev/initialScale: "1"
              autoscaling.knative.dev/minScale: "1"
          spec:
            serviceAccountName: git-webhook
