apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  annotations:
    external-dns-namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts: {{ include "runhub.hosts" . | nindent 8 }}
      port:
        name: http
        protocol: HTTP
        number: 80
      tls:
        httpsRedirect: true
    - hosts: {{ include "runhub.hosts" . | nindent 8 }}
      port:
        name: https
        protocol: HTTPS
        number: 443
      tls:
        mode: SIMPLE
        credentialName: {{ .Release.Namespace }}--certificate-tls
