apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-app
  namespace: {{ $.Release.Namespace }}-app
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
      - update
      - delete
