apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build
rules:
  - apiGroups: 
      - tekton.dev
    resources:
      - pipelines
      - tasks
    verbs:
      - get
      - create
      - patch
      - delete
  - apiGroups: 
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - list
      - get
      - create
      - watch
  - apiGroups: 
      - tekton.dev
    resources:
      - taskruns
    verbs:
      - list
      - get
      - watch
  - apiGroups: 
      - ''
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
      - watch
  - apiGroups: 
      - tekton.dev
    resources:
      - pipelineresources
    verbs:
      - list
