apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: undeploy
  namespace: {{ template "runhub.env" $ }}-{{ $.Release.Name }}-app
rules:
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - delete
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - delete
