apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: undeploy-app
  namespace: {{ $.Release.Namespace }}-app
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - list
      - get
      - update
      - delete
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
    verbs:
      - delete
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - delete
