apiVersion: v1
kind: Secret
metadata:
  name: git-webhook-opaque
  namespace: {{ template "runhub.namespaceReleaseChart" . }}
type: Opaque
data:
  secret: '
    {{- $gitWebhookOpaque := lookup "v1" "Secret" .Release.Namespace "git-webhook-opaque" }}
    {{- if $gitWebhookOpaque }}
      {{- $gitWebhookOpaque.data.secret }}
    {{- else }}
      {{- randAlphaNum 40 | b64enc }}
    {{- end -}}
  '
