apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    autoscaler:
      allow-zero-initial-scale: "true"
    config-certmanager:
       issuerRef: |
        kind: Issuer
        name: issuer
    network:
      domainTemplate: |-
        {{"{{"}} if index .Annotations "domain" -}}
          {{"{{"}} .Name }}.{{"{{"}} index .Annotations "domain" }}
        {{"{{"}}- else -}}
          {{"{{"}} .Name }}.{{"{{"}} .Namespace }}.{{"{{"}} .Domain }}
        {{"{{"}}- end }}
      autoTLS: "Enabled"
      httpProtocol: "Redirected"
  additionalManifests:
    - URL: https://github.com/knative-sandbox/net-certmanager/releases/download/v${VERSION}/net-certmanager.yaml
