apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-webhook
  namespace: {{ template "runhub.namespaceEnvReleaseChart" . }}
rules:
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggers
      - triggerbindings
      - triggertemplates
    verbs:
      - list
      - get
      - watch
  - apiGroups: 
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
