apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy-on-git-push-branch
spec:
  params:
    - name: git-revision
      value: $(body.ref)
    - name: tag
      value: br-$(extensions.branch)
    - name: cache-from-tag
      value: br-$(extensions.cache-from-branch)
    - name: environment
      value: $(extensions.environment)
