apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: runhub
spec:
  servers:
    - hosts:
        - git-webhook.runhub.{{ .Values.domain }}
      port:
        name: http
        protocol: HTTP
        number: 80
    {{- if .Values.global.tls }}
      tls:
        httpsRedirect: true
    - hosts:
        - git-webhook.runhub.{{ .Values.domain }}
      port:
        name: https
        protocol: HTTPS
        number: 443
      tls:
        mode: SIMPLE
        credentialName: {{ .Release.Namespace }}--certificate-tls
    {{- end}}
