apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-webhook
  namespace: {{ template "runhub-app.namespaceEnvironmentReleaseChart" . }}
spec:
  triggers:
    - triggerRef: build-deploy-on-git-ping
    - triggerRef: build-deploy-on-git-push-branch
    - triggerRef: undeploy-on-git-push-delete-branch
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: git-webhook
