apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: subroute-tag
    - name: image-tag
    - name: cache-from-image-tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-$(tt.params.image-tag)-
      spec:
        serviceAccountName: build-deploy
        pipelineRef:
          name: build-deploy
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: subroute-tag
            value: $(tt.params.subroute-tag)
          - name: image-tag
            value: $(tt.params.image-tag)
          - name: cache-from-image-tag
            value: $(tt.params.cache-from-image-tag)
        workspaces:
          - name: dockerfile
            configMap:
              name: dockerfile
          - name: src
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
