apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: route-tag
    - name: image-tag
    - name: cache-from-image-tag
    - name: main-route-tag
    - name: main-route-image-tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-
      spec:
        serviceAccountName: build-deploy
        pipelineRef:
          name: build-deploy
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: route-tag
            value: $(tt.params.route-tag)
          - name: image-tag
            value: $(tt.params.image-tag)
          - name: cache-from-image-tag
            value: $(tt.params.cache-from-image-tag)
          - name: main-route-tag
            value: $(tt.params.main-route-tag)
          - name: main-route-image-tag
            value: $(tt.params.main-route-image-tag)
        workspaces:
          - name: src
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
