apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: tag
      type: string
    - name: cache-from-tag
      type: string
    - name: env
      type: string
    - name: git-default-branch
      type: string
  workspaces:
  {{- range $serviceName, $service := .Values.global.services }}
    - name: build-context-{{ $serviceName }}
  {{- end }}
    - name: build-tools
  {{- if (and .Values.release .Values.release.prodKubernetesCredentials) }}
    - name: prod-kubeconfig
  {{- end }}
  tasks:
    - name: sanitize-tag
      taskRef:
        name: sanitize
      params:
        - name: input
          value: $(params.tag)
    - name: sanitize-cache-from-tag
      taskRef:
        name: sanitize
      params:
        - name: input
          value: $(params.cache-from-tag)
    - name: validate
      runAfter:
        - sanitize-tag
        - sanitize-cache-from-tag
      taskRef:
        name: validate
      params:
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
        - name: env
          value: $(params.env)
  {{- range $serviceName, $service := .Values.global.services }}
    - name: build-{{ $serviceName }}
      runAfter:
        - validate
      taskRef:
        name: build
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: service
          value: {{ $serviceName }}
        - name: service-src-path
          value: {{ $service.srcPath }}
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
        - name: cache-from-tag
          value: $(tasks.sanitize-cache-from-tag.results.output)
      workspaces:
        - name: context
          workspace: build-context-{{ $serviceName }}
        - name: build-tools
          workspace: build-tools
    - name: get-sha-{{ $serviceName }}
      runAfter:
        - build-{{ $serviceName }}
      taskRef:
        name: get-sha
      params:
        - name: service
          value: {{ $serviceName }}
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
    - name: deploy-{{ $serviceName }}
      runAfter:
      {{- range $serviceName, $service := $.Values.global.services }}
        - get-sha-{{ $serviceName }}
      {{- end }}
        - provision
      taskRef:
        name: deploy
      params:
        - name: service
          value: {{ $serviceName }}
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
        - name: sha
          value: $(tasks.get-sha-{{ $serviceName }}.results.sha)
        - name: env
          value: $(params.env)
    {{- if (and $.Values.release $.Values.release.prodKubernetesCredentials) }}
      workspaces:
        - name: prod-kubeconfig
          workspace: prod-kubeconfig
    {{- end }}
    - name: expose-{{ $serviceName }}
      runAfter:
      {{- range $serviceName, $service := $.Values.global.services }}
        - deploy-{{ $serviceName }}
      {{- end }}
      taskRef:
        name: expose
      params:
        - name: service
          value: {{ $serviceName }}
        - name: subdomain
          value: {{ $service.subdomain }}
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
        - name: env
          value: $(params.env)
    {{- if (and $.Values.release $.Values.release.prodKubernetesCredentials) }}
      workspaces:
        - name: prod-kubeconfig
          workspace: prod-kubeconfig
    {{- end }}
  {{- end }}
    - name: provision
      taskRef:
        name: provision
      params:
        - name: services-count
          value: '{{ len .Values.global.services }}'
        - name: env
          value: $(params.env)
        - name: tag
          value: $(params.tag)
        - name: git-default-branch
          value: $(params.git-default-branch)
    {{- if (and .Values.release .Values.release.prodKubernetesCredentials) }}
      workspaces:
        - name: prod-kubeconfig
          workspace: prod-kubeconfig
    {{- end }}
