apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: undeploy
spec:
  params:
    - name: tag
      type: string
  tasks:
    - name: sanitize-tag
      taskRef:
        name: sanitize
      params:
        - name: input
          value: $(params.tag)
    - name: validate
      runAfter:
        - sanitize-tag
      taskRef:
        name: validate
      params:
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
        - name: env
          value: dev
    - name: uninstall
      runAfter:
        - validate
      taskRef:
        name: uninstall
      params:
        - name: tag
          value: $(tasks.sanitize-tag.results.output)
