apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: build-deploy-on-git-ping
spec:
  interceptors:
    - github:
        secretRef:
          secretName: git-webhook-opaque
          secretKey: secret
        eventTypes:
          - ping
    - cel:
        overlays:
          - key: env
            expression: |
            {{- if (and .Values.release .Values.global.prodDomain) }}
              body.repository.default_branch == '{{ .Values.release.prodBranch }}' ? 'prod' : 'dev'
            {{- else }}
              'dev'
            {{- end }}
  bindings:
    - ref: build-deploy-on-git
    - ref: build-deploy-on-git-ping
  template:
    ref: build-deploy
