apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: build-deploy-on-git-push-branch
spec:
  interceptors:
    - github:
        secretRef:
          secretName: git-webhook-opaque
          secretKey: secret
        eventTypes:
          - push
    - cel:
        overlays:
          - key: ref_type
            expression: body.ref.split('/', 3)[1]
          - key: base_ref_type
            expression: |
              type(body.base_ref) != string ? '' : body.base_ref.split('/', 3)[1]
          - key: branch
            expression: body.ref.split('/', 3)[2]
          - key: base_branch
            expression: |
              type(body.base_ref) != string ? '' : body.base_ref.split('/', 3)[2]
    - cel:
        filter: extensions.ref_type == 'heads' && !body.deleted
        overlays:
          - key: cache-from-branch
            expression: |
              extensions.base_ref_type == 'heads'
                ? extensions.base_branch
                : body.repository.default_branch
          - key: env
            expression: |
            {{- if (and .Values.release .Values.global.prodDomain) }}
              extensions.branch == '{{ .Values.release.prodBranch }}' ? 'prod' : 'dev'
            {{- else }}
              'dev'
            {{- end }}
  bindings:
    - ref: build-deploy-on-git
    - ref: build-deploy-on-git-push-branch
  template:
    ref: build-deploy
