apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-deploy
secrets:
{{- if .Values.gitCredentials }}
  - name: git-basic-auth
{{- end }}
  - name: container-registry-dockerconfigjson
{{- if (and .Values.release .Values.release.prodKubernetesCredentials) }}
  - name: prod-kubeconfig-opaque
{{- end }}
