apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: git-webhook
spec:
  triggers:
    - triggerRef: build-deploy-on-git-ping
    - triggerRef: build-deploy-on-git-push-branch
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
      spec:
        template:
          spec:
            serviceAccountName: git-webhook
