{{- $namespace := include "runhub.namespaceEnvReleaseChart" . }}
apiVersion: v1
kind: Secret
metadata:
  name: git-webhook-opaque
  namespace: {{ $namespace }}
type: Opaque
data:
  secret: '
    {{- $gitWebhookOpaque := lookup "v1" "Secret" $namespace "git-webhook-opaque" }}
    {{- if $gitWebhookOpaque }}
      {{- $gitWebhookOpaque.data.secret }}
    {{- else }}
      {{- randAlphaNum 40 | b64enc }}
    {{- end -}}
  '
