apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: git-webhook
spec:
  gateways:
    - gateway
  hosts:
    - git-webhook.runhub.{{ .Values.domain }}
  http:
    - rewrite:
        authority: el-git-webhook.{{ .Release.Namespace }}.svc.cluster.local
      route:
        - destination:
            host: el-git-webhook.{{ .Release.Namespace }}.svc.cluster.local
